apiVersion: v1
kind: Pod
metadata:
  name: secret
spec:
  containers:
  - name: mycontainer
    image: mysql
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: helloworld-secrets
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: helloworld-secrets
            key: password
      - name: SECRET_ROOTPASSWORD
        valueFrom:
          secretKeyRef:
            name: helloworld-secrets
            key: rootpassoword
      - name: SECRET_DATABASE
        valueFrom:
          secretKeyRef:
            name: helloworld-secrets
            key: database
  
