apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: balaji-nginx
    image: nginx:1.21.3
    ports:
    - containerPort: 8080
  - name: pod2
    image: afakharany/watcher
    
